"""Initial schema definition

Revision ID: d48a5b99342e
Revises: 
Create Date: 2024-05-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'd48a5b99342e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_jobs_uid'), 'failed_jobs', ['uid'], unique=False)
    op.create_table('page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_raw_uid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('last_processed', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_content_page_raw_uid'), 'page_content', ['page_raw_uid'], unique=False)
    op.create_table('page_embeddings_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_content_id', sa.Integer(), nullable=False),
    sa.Column('chunk', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_content_id', sa.Integer(), nullable=False),
    sa.Column('keywords_tsvector', sa.dialects.postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_keywords_page_content_id'), 'page_keywords', ['page_content_id'], unique=False)
    op.create_index('idx_keywords_tsvector', 'page_keywords', ['keywords_tsvector'], unique=False, postgresql_using='gin')
    op.create_table('page_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_raw_uid'), 'page_raw', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_raw_uid'), table_name='page_raw')
    op.drop_table('page_raw')
    op.drop_index('idx_keywords_tsvector', table_name='page_keywords')
    op.drop_index(op.f('ix_page_keywords_page_content_id'), table_name='page_keywords')
    op.drop_table('page_keywords')
    op.drop_table('page_embeddings_a')
    op.drop_index(op.f('ix_page_content_page_raw_uid'), table_name='page_content')
    op.drop_table('page_content')
    op.drop_index(op.f('ix_failed_jobs_uid'), table_name='failed_jobs')
    op.drop_table('failed_jobs')
    # ### end Alembic commands ### 